name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Mise à jour v4 (plus de soulignement)

      - name: Set up Python
        uses: actions/setup-python@v5 # Mise à jour v5
        with:
          python-version: "3.12"
          cache: 'pip' # Accélère les builds suivants

      - name: Install project and dependencies
        run: |
          python -m pip install --upgrade pip
          # Installation du projet en mode éditable pour lier le dossier 'src'
          pip install -e .
          # Installation des dépendances de test
          pip install pytest pytest-cov httpx pandas fastapi uvicorn pydantic python-dotenv

      - name: Run Tests with Coverage
        run: |
          # On définit explicitement le PYTHONPATH pour GitHub
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python -m pytest --cov=src