name: Python Checks

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installation des bibliothèques nécessaires
          pip install pytest fastapi uvicorn pandas httpx

      - name: Prepare Workspace
        # On recrée l'environnement de données pour les tests
        run: |
          mkdir -p data
          echo "amount,use_chip,isFraud" > data/transactions_data.csv
          echo "10.0,Swipe Transaction,0" >> data/transactions_data.csv

      - name: Run Tests
        # CORRECTION CRUCIALE : On pointe vers 'src' pour trouver le code
        env:
          PYTHONPATH: src
        run: |
          pytest